language: go

go:
  - "1.10.2"

sudo: required
env:
  - "PATH=/home/travis/gopath/bin:$PATH"

before_install:
  - go get -v github.com/netc0/netco

install:
  - # skip

before_script:
  - sudo ntpdate -u time.google.com
  - date

script:
  - echo "script"
  - go test -p 1 -tags json -v ./...
  - go test -race -coverprofile=coverage.txt -covermode=atomic
after_success:
  - echo "success"
  - bash <(curl -s https://codecov.io/bash) -t bde232f1-4555-45b0-9e79-58deeb6eaa4d