language: go

go:
  - "1.10.2"

sudo: required

before_install:
  - export GOPATH=$HOME/gopath/src/github.com/netc0/gate
  - export PATH=$PATH:$HOME/gopath/src/github.com/netc0/gate/bin
  - go get -v github.com/netc0/netco

install:
  - # skip

before_script:
  - sudo ntpdate -u time.google.com
  - date
  - go vet ./...

script:
  - echo "script"
  - go get -t -v ./...
  - go test -v -race ./...